# Generated by Django 5.0.7 on 2026-07-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='prices',
        ),
    ]
