"""Squashed history for `portfolio`: 29 migrations collapsed into the schema they
add up to (see `replaces` below).

Every replaced migration's one-shot data repair -- purges, backfills, dedupes --
is deliberately dropped. Each already ran on every deployed database, and on a
fresh one there is nothing for it to repair.
"""
# Generated by Django 5.2.16 on 2026-08-20 16:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    replaces = [
        ("portfolio", "0001_initial"),
        ("portfolio", "0002_transaction"),
        ("portfolio", "0003_account_goal"),
        ("portfolio", "0004_holding_area_sqm_holding_mortgage_deduction_tomans"),
        ("portfolio", "0005_snapshot_is_estimated"),
        ("portfolio", "0006_alter_snapshot_timestamp"),
        ("portfolio", "0007_transaction_created_at_transaction_source_and_more"),
        ("portfolio", "0008_backtestrun_backtestyear"),
        ("portfolio", "0009_backtestrun_universe"),
        ("portfolio", "0010_watchlist_watchlistitem_and_more"),
        ("portfolio", "0011_backtestuserquota_and_more"),
        ("portfolio", "0012_trust_first_ledger"),
        ("portfolio", "0013_ledger_constraints"),
        ("portfolio", "0014_backtest_contract"),
        ("portfolio", "0015_ledger_real_estate_baseline"),
        ("portfolio", "0016_backtest_real_toman"),
        ("portfolio", "0017_alter_holding_mortgage_deduction_tomans_liability"),
        ("portfolio", "0018_alter_ledgerentry_reversal_of"),
        ("portfolio", "0019_delete_backtest_watchlist"),
        ("portfolio", "0020_add_price_unit_fields"),
        ("portfolio", "0021_backfill_price_unit"),
        ("portfolio", "0022_alter_price_price_unit_and_more"),
        ("portfolio", "0023_snapshot_idx_snapshot_user_acct_time"),
        ("portfolio", "0024_optimizationsnapshot_window_days"),
        ("portfolio", "0025_house_valuation_marks"),
        ("portfolio", "0026_asset_proxy_key"),
        ("portfolio", "0027_backfill_snapshot_liability_netting"),
        ("portfolio", "0028_dailypriceaverage"),
        ("portfolio", "0029_snapshot_session_close"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_fa', models.CharField(blank=True, default='', max_length=120)),
                ('asset_class', models.CharField(choices=[('Gold', 'Gold'), ('Cash', 'Cash / Currency'), ('Stock', 'Stock'), ('Real Estate', 'Real Estate'), ('Crypto', 'Crypto')], default='Gold', max_length=16)),
                ('currency', models.CharField(choices=[('IRT', 'Tomans'), ('USD', 'USD')], default='IRT', max_length=3)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_house', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tse_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('brs_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('proxy_key', models.SlugField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('broker', models.CharField(blank=True, default='', max_length=120)),
                ('goal', models.CharField(blank=True, default='', max_length=40)),
                ('tracking_started_at', models.DateTimeField(blank=True, null=True)),
                ('cash_balance_tomans', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('ledger_complete', models.BooleanField(default=False, help_text='True when opening balances and subsequent cash flows are complete.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPriceAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_price_averages', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('area_sqm', models.DecimalField(decimal_places=2, default=Decimal('90.2'), max_digits=10)),
                ('mortgage_deduction_tomans', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.asset')),
            ],
            options={
                'ordering': ['asset__asset_class', 'asset__name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='portfolio.account')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening_position', 'Opening position'), ('opening_cash', 'Opening cash'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('valuation_mark', 'Valuation mark')], max_length=24)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price_tomans', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('amount_tomans', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mortgage_deduction_tomans', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('csv', 'csv'), ('system', 'system'), ('imported', 'imported (legacy)'), ('inferred', 'inferred (legacy)')], default='manual', max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.account')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='portfolio.importbatch')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversed_by', to='portfolio.ledgerentry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount_tomans', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='portfolio.account')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='portfolio.asset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario', models.CharField(choices=[('max_sharpe', 'Max Sharpe'), ('min_volatility', 'Min Volatility'), ('equal_weight', 'Equal Weight'), ('risk_parity', 'Risk Parity'), ('hrp', 'HRP')], default='max_sharpe', max_length=32)),
                ('window_days', models.PositiveIntegerField(db_index=True, default=180)),
                ('payload', models.JSONField()),
                ('price_version', models.CharField(blank=True, default='', max_length=64)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_snapshots', to='portfolio.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_optimization_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(default='API', max_length=16)),
                ('price_unit', models.CharField(choices=[('IRT', 'Tomans'), ('IRR', 'Rials'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Declared unit for this price value (IRT=Tomans, IRR=Rials, UNKNOWN)', max_length=16)),
                ('price_unit_verified', models.BooleanField(default=False, help_text='True when a human or automated check has verified the unit for this provider/asset')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value_tomans', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_estimated', models.BooleanField(default=False, help_text='True for downtime-gap backfilled rows (fabricated from recovery-time prices, not real history).')),
                ('is_session_close', models.BooleanField(default=False, help_text='True when every held TSE asset used the verified close for its completed session.')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_account_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='dailypriceaverage',
            index=models.Index(fields=['asset', '-date'], name='daily_price_avg_asset_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailypriceaverage',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='uniq_daily_price_average_asset_date'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('account', 'asset'), name='uniq_asset_per_account'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('account', 'file_hash'), name='uniq_import_file_per_account'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-timestamp'], name='idx_txn_account_time'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['opening_position', 'buy', 'sell', 'valuation_mark']), _negated=True), models.Q(('asset__isnull', False), ('quantity__isnull', False), ('quantity__gt', 0)), _connector='OR'), name='ledger_asset_event_fields'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dividend'), _negated=True), ('asset__isnull', False), _connector='OR'), name='ledger_dividend_asset'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['opening_cash', 'deposit', 'withdrawal', 'dividend', 'fee']), _negated=True), ('amount_tomans__gt', 0), _connector='OR'), name='ledger_cash_event_amount'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('account', 'external_id'), name='uniq_ledger_external_id_per_account'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['asset', '-fetched_at'], name='idx_price_asset_time'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['user', '-timestamp'], name='idx_snapshot_user_time'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['user', 'account', 'timestamp'], name='idx_snapshot_user_acct_time'),
        ),
    ]
# Generated by Django 5.2.16 on 2026-08-20 16:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_fa', models.CharField(blank=True, default='', max_length=120)),
                ('asset_class', models.CharField(choices=[('Gold', 'Gold'), ('Cash', 'Cash / Currency'), ('Stock', 'Stock'), ('Real Estate', 'Real Estate'), ('Crypto', 'Crypto')], default='Gold', max_length=16)),
                ('currency', models.CharField(choices=[('IRT', 'Tomans'), ('USD', 'USD')], default='IRT', max_length=3)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_house', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tse_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('brs_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('proxy_key', models.SlugField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('broker', models.CharField(blank=True, default='', max_length=120)),
                ('goal', models.CharField(blank=True, default='', max_length=40)),
                ('tracking_started_at', models.DateTimeField(blank=True, null=True)),
                ('cash_balance_tomans', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('ledger_complete', models.BooleanField(default=False, help_text='True when opening balances and subsequent cash flows are complete.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPriceAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_price_averages', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('area_sqm', models.DecimalField(decimal_places=2, default=Decimal('90.2'), max_digits=10)),
                ('mortgage_deduction_tomans', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.asset')),
            ],
            options={
                'ordering': ['asset__asset_class', 'asset__name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='portfolio.account')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening_position', 'Opening position'), ('opening_cash', 'Opening cash'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('valuation_mark', 'Valuation mark')], max_length=24)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price_tomans', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('amount_tomans', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mortgage_deduction_tomans', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('csv', 'csv'), ('system', 'system'), ('imported', 'imported (legacy)'), ('inferred', 'inferred (legacy)')], default='manual', max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.account')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='portfolio.importbatch')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversed_by', to='portfolio.ledgerentry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount_tomans', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='portfolio.account')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='portfolio.asset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario', models.CharField(choices=[('max_sharpe', 'Max Sharpe'), ('min_volatility', 'Min Volatility'), ('equal_weight', 'Equal Weight'), ('risk_parity', 'Risk Parity'), ('hrp', 'HRP')], default='max_sharpe', max_length=32)),
                ('window_days', models.PositiveIntegerField(db_index=True, default=180)),
                ('payload', models.JSONField()),
                ('price_version', models.CharField(blank=True, default='', max_length=64)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_snapshots', to='portfolio.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_optimization_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(default='API', max_length=16)),
                ('price_unit', models.CharField(choices=[('IRT', 'Tomans'), ('IRR', 'Rials'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Declared unit for this price value (IRT=Tomans, IRR=Rials, UNKNOWN)', max_length=16)),
                ('price_unit_verified', models.BooleanField(default=False, help_text='True when a human or automated check has verified the unit for this provider/asset')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value_tomans', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_estimated', models.BooleanField(default=False, help_text='True for downtime-gap backfilled rows (fabricated from recovery-time prices, not real history).')),
                ('is_session_close', models.BooleanField(default=False, help_text='True when every held TSE asset used the verified close for its completed session.')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_account_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='dailypriceaverage',
            index=models.Index(fields=['asset', '-date'], name='daily_price_avg_asset_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailypriceaverage',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='uniq_daily_price_average_asset_date'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('account', 'asset'), name='uniq_asset_per_account'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('account', 'file_hash'), name='uniq_import_file_per_account'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-timestamp'], name='idx_txn_account_time'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['opening_position', 'buy', 'sell', 'valuation_mark']), _negated=True), models.Q(('asset__isnull', False), ('quantity__isnull', False), ('quantity__gt', 0)), _connector='OR'), name='ledger_asset_event_fields'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dividend'), _negated=True), ('asset__isnull', False), _connector='OR'), name='ledger_dividend_asset'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['opening_cash', 'deposit', 'withdrawal', 'dividend', 'fee']), _negated=True), ('amount_tomans__gt', 0), _connector='OR'), name='ledger_cash_event_amount'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('account', 'external_id'), name='uniq_ledger_external_id_per_account'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['asset', '-fetched_at'], name='idx_price_asset_time'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['user', '-timestamp'], name='idx_snapshot_user_time'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['user', 'account', 'timestamp'], name='idx_snapshot_user_acct_time'),
        ),
    ]
