# Generated by Django 5.0.7 on 2026-07-23 15:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_account_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='area_sqm',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.2'), max_digits=10),
        ),
        migrations.AddField(
            model_name='holding',
            name='mortgage_deduction_tomans',
            field=models.DecimalField(decimal_places=4, default=Decimal('400000000'), max_digits=20),
        ),
    ]
