# Generated by Django 5.0.7 on 2026-07-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_holding_area_sqm_holding_mortgage_deduction_tomans'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='is_estimated',
            field=models.BooleanField(default=False, help_text='True for downtime-gap backfilled rows (fabricated from recovery-time prices, not real history).'),
        ),
    ]
