# Generated by Django 5.0.7 on 2026-08-01 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_transaction_created_at_transaction_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_hash', models.CharField(db_index=True, max_length=64)),
                ('basis', models.CharField(choices=[('nominal', 'nominal'), ('usd_real', 'usd_real')], default='nominal', max_length=16)),
                ('universe_hash', models.CharField(max_length=64)),
                ('integrity_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.CharField(max_length=32)),
                ('scenario', models.CharField(max_length=32)),
                ('target_weights', models.JSONField()),
                ('realized_metrics', models.JSONField()),
                ('benchmark_delta', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('excluded_symbols', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='portfolio.backtestrun')),
            ],
            options={
                'ordering': ['cutoff_date', 'scenario'],
            },
        ),
    ]
