# Generated by Django 5.0.7 on 2026-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_backtestrun_backtestyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='universe',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
