# Generated by Django 5.0.7 on 2026-08-02 19:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_mortgages_to_liabilities(apps, schema_editor):
    Holding = apps.get_model('portfolio', 'Holding')
    Liability = apps.get_model('portfolio', 'Liability')
    
    for holding in Holding.objects.filter(mortgage_deduction_tomans__gt=0):
        Liability.objects.create(
            account=holding.account,
            label=f"Mortgage ({holding.asset.name})",
            amount_tomans=holding.mortgage_deduction_tomans,
            asset=holding.asset,
        )
        holding.mortgage_deduction_tomans = Decimal('0')
        holding.save(update_fields=['mortgage_deduction_tomans'])


def reverse_migrate_mortgages(apps, schema_editor):
    Holding = apps.get_model('portfolio', 'Holding')
    Liability = apps.get_model('portfolio', 'Liability')
    
    for liability in Liability.objects.filter(asset__isnull=False, label__startswith="Mortgage"):
        holding = Holding.objects.filter(account=liability.account, asset=liability.asset).first()
        if holding:
            holding.mortgage_deduction_tomans = liability.amount_tomans
            holding.save(update_fields=['mortgage_deduction_tomans'])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_backtest_real_toman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount_tomans', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='portfolio.account')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='portfolio.asset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(migrate_mortgages_to_liabilities, reverse_migrate_mortgages),
        migrations.AlterField(
            model_name='holding',
            name='mortgage_deduction_tomans',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20),
        ),
    ]
