# Generated by Django 5.0.7 on 2026-08-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_holding_mortgage_deduction_tomans_liability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversed_by', to='portfolio.ledgerentry'),
        ),
    ]
