# Generated by Django 5.0.7 on 2026-08-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_ledgerentry_reversal_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestyear',
            name='run',
        ),
        migrations.RemoveField(
            model_name='backtestuserquota',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='account',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='BacktestRun',
        ),
        migrations.DeleteModel(
            name='BacktestYear',
        ),
        migrations.DeleteModel(
            name='BacktestUserQuota',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
