# Generated by Copilot CLI on 2026-08-04
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_delete_backtest_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_unit',
            field=models.CharField(choices=[('IRT', 'Tomans'), ('IRR', 'Rials'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='price',
            name='price_unit_verified',
            field=models.BooleanField(default=False),
        ),
    ]
