# Generated by Django 5.0.7 on 2026-08-04 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_backfill_price_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_unit',
            field=models.CharField(choices=[('IRT', 'Tomans'), ('IRR', 'Rials'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Declared unit for this price value (IRT=Tomans, IRR=Rials, UNKNOWN)', max_length=16),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_unit_verified',
            field=models.BooleanField(default=False, help_text='True when a human or automated check has verified the unit for this provider/asset'),
        ),
        migrations.CreateModel(
            name='OptimizationSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario', models.CharField(choices=[('max_sharpe', 'Max Sharpe'), ('min_volatility', 'Min Volatility'), ('equal_weight', 'Equal Weight'), ('risk_parity', 'Risk Parity'), ('hrp', 'HRP')], default='max_sharpe', max_length=32)),
                ('payload', models.JSONField()),
                ('price_version', models.CharField(blank=True, default='', max_length=64)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_snapshots', to='portfolio.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_optimization_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
