# Generated by Django 5.0.7 on 2026-08-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_price_price_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['user', 'account', 'timestamp'], name='idx_snapshot_user_acct_time'),
        ),
    ]
