# Generated by Django 5.0.7 on 2026-08-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_snapshot_idx_snapshot_user_acct_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationsnapshot',
            name='window_days',
            field=models.PositiveIntegerField(db_index=True, default=180),
        ),
    ]
