# Generated by Django 5.2.16 on 2026-08-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_optimizationsnapshot_window_days'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledger_asset_event_fields',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('opening_position', 'Opening position'), ('opening_cash', 'Opening cash'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('valuation_mark', 'Valuation mark')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['opening_position', 'buy', 'sell', 'valuation_mark']), _negated=True), models.Q(('asset__isnull', False), ('quantity__isnull', False), ('quantity__gt', 0)), _connector='OR'), name='ledger_asset_event_fields'),
        ),
    ]
