# Generated by Django 5.2.16 on 2026-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_house_valuation_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='proxy_key',
            field=models.SlugField(blank=True, default='', max_length=64),
        ),
    ]
