# Generated by Django 5.2.16 on 2026-08-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_backfill_snapshot_liability_netting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPriceAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_price_averages', to='portfolio.asset')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['asset', '-date'], name='daily_price_avg_asset_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date'), name='uniq_daily_price_average_asset_date')],
            },
        ),
    ]
