# Generated by Django 5.2.16 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_dailypriceaverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="is_session_close",
            field=models.BooleanField(
                default=False,
                help_text="True when every held TSE asset used the verified close for its completed session.",
            ),
        ),
    ]
