# Generated by Django 5.2.17 on 2026-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0047_ledger_removal_history"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ledgerentry",
            name="uniq_ledger_external_id_per_account",
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("external_id", ""), _negated=True),
                    ("removed_at__isnull", True),
                ),
                fields=("account", "external_id"),
                name="uniq_ledger_external_id_per_account",
            ),
        ),
    ]
