# Generated by Django 5.2.17 on 2026-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestPerfRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.DateTimeField(help_text="UTC start of the hour.")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API request (server-measured)"),
                            ("client_api", "API call (browser-measured)"),
                            ("client_page", "Page ready (browser-measured)"),
                            ("client_boot", "App boot (browser-measured)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("route", models.CharField(max_length=160)),
                ("method", models.CharField(default="", max_length=8)),
                ("market_state", models.CharField(default="", max_length=16)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "errors",
                    models.PositiveIntegerField(default=0, help_text="5xx / failed"),
                ),
                (
                    "client_errors",
                    models.PositiveIntegerField(default=0, help_text="4xx"),
                ),
                ("sum_ms", models.FloatField(default=0)),
                ("max_ms", models.FloatField(default=0)),
                ("sum_db_queries", models.BigIntegerField(default=0)),
                ("sum_db_ms", models.FloatField(default=0)),
                ("sum_inflight", models.BigIntegerField(default=0)),
                ("hist", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-bucket"],
                "indexes": [
                    models.Index(
                        fields=["source", "bucket"],
                        name="perf_reques_source_4f221b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket", "source", "route", "method", "market_state"),
                        name="uniq_perf_rollup_dims",
                    )
                ],
            },
        ),
    ]
