# Generated by Django 5.0.7 on 2026-08-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_closed_beta_identity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
