# Generated by Django 5.2.16 on 2026-08-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_google_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pro_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
    ]
