# Generated by Django 5.2.16 on 2026-08-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_pro_expires_at_remove_user_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_sub',
        ),
    ]
