# Generated by Django 5.2.16 on 2026-09-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchBudgetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('spent_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=64)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('answered', 'Answered'), ('abstained', 'Abstained'), ('failed', 'Failed')], default='running', max_length=16)),
                ('max_cost_usd', models.DecimalField(decimal_places=6, max_digits=8)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('actual_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('cost_basis', models.CharField(blank=True, default='', max_length=24)),
                ('provider_model', models.CharField(blank=True, default='', max_length=128)),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_observations', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='research_re_user_id_246887_idx')],
            },
        ),
    ]
