from django.urls import path
from .views import (
    AdminPasswordResetLinkView,
    AdminUserDetailView,
    AdminUserListView,
    ChangePasswordView,
    CookieTokenObtainPairView,
    CsrfView,
    ExportView,
    LogoutAllView,
    LogoutView,
    MeView,
    MobileChangePasswordView,
    MobileLogoutView,
    MobileLogoutAllView,
    MobileRegisterView,
    MobileTokenObtainPairView,
    MobileTokenRefreshView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RegisterView,
    RegistrationStatusView,
)

urlpatterns = [
    path("mobile/register/", MobileRegisterView.as_view(), name="mobile-register"),
    path("mobile/login/", MobileTokenObtainPairView.as_view(), name="mobile-login"),
    path("mobile/refresh/", MobileTokenRefreshView.as_view(), name="mobile-refresh"),
    path("mobile/logout/", MobileLogoutView.as_view(), name="mobile-logout"),
    path("mobile/logout-all/", MobileLogoutAllView.as_view(), name="mobile-logout-all"),
    path("mobile/change-password/", MobileChangePasswordView.as_view(), name="mobile-change-password"),
    path("register/", RegisterView.as_view(), name="register"),
    path("registration/", RegistrationStatusView.as_view(), name="registration-status"),
    path("export/", ExportView.as_view(), name="export"),
    path("login/", CookieTokenObtainPairView.as_view(), name="login"),
    path("csrf/", CsrfView.as_view(), name="csrf"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("logout-all/", LogoutAllView.as_view(), name="logout-all"),
    path("me/", MeView.as_view(), name="me"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("password-reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path(
        "password-reset/confirm/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path(
        "admin/users/<int:pk>/",
        AdminUserDetailView.as_view(),
        name="admin-user-detail",
    ),
    path(
        "admin/password-reset-link/",
        AdminPasswordResetLinkView.as_view(),
        name="admin-password-reset-link",
    ),
]
