# Generated by Django 5.0.7 on 2026-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField()),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('date_title', models.CharField(blank=True, default='', max_length=20)),
                ('date_send', models.CharField(blank=True, default='', max_length=10)),
                ('time_send', models.CharField(blank=True, default='', max_length=8)),
                ('date_publish', models.CharField(blank=True, default='', max_length=10)),
                ('time_publish', models.CharField(blank=True, default='', max_length=8)),
                ('link', models.URLField(blank=True, default='', max_length=1024)),
                ('link_pdf', models.URLField(blank=True, default='', max_length=1024)),
                ('link_excel', models.URLField(blank=True, default='', max_length=1024)),
                ('link_attachment', models.URLField(blank=True, default='', max_length=1024)),
            ],
            options={
                'ordering': ['-date_publish', '-time_publish'],
            },
        ),
        migrations.CreateModel(
            name='DailyStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('time', models.CharField(blank=True, default='', max_length=8)),
                ('tno', models.IntegerField(default=0)),
                ('tvol', models.BigIntegerField(default=0)),
                ('tval', models.BigIntegerField(default=0)),
                ('pmin', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pmax', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('py', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pf', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pl', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('plc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('plp', models.FloatField(default=0.0)),
                ('pc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pcc', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pcp', models.FloatField(default=0.0)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('buy_count_i', models.IntegerField(blank=True, null=True)),
                ('buy_count_n', models.IntegerField(blank=True, null=True)),
                ('sell_count_i', models.IntegerField(blank=True, null=True)),
                ('sell_count_n', models.IntegerField(blank=True, null=True)),
                ('buy_i_volume', models.BigIntegerField(blank=True, null=True)),
                ('buy_n_volume', models.BigIntegerField(blank=True, null=True)),
                ('sell_i_volume', models.BigIntegerField(blank=True, null=True)),
                ('sell_n_volume', models.BigIntegerField(blank=True, null=True)),
                ('buy_i_value', models.BigIntegerField(blank=True, null=True)),
                ('buy_n_value', models.BigIntegerField(blank=True, null=True)),
                ('sell_i_value', models.BigIntegerField(blank=True, null=True)),
                ('sell_n_value', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GoldCurrencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('close_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('timeframe', models.CharField(db_index=True, max_length=16)),
                ('date_time', models.CharField(db_index=True, max_length=32)),
                ('open_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='MarketIndexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('time', models.CharField(blank=True, default='', max_length=8)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('index_overall', models.FloatField(default=0.0)),
                ('index_overall_change', models.FloatField(default=0.0)),
                ('index_equal_weight', models.FloatField(default=0.0)),
                ('index_equal_weight_change', models.FloatField(default=0.0)),
                ('market_value', models.BigIntegerField(default=0)),
                ('trade_number', models.IntegerField(default=0)),
                ('trade_value', models.BigIntegerField(default=0)),
                ('trade_volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ShareholderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('shareholder_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('volume', models.BigIntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
            options={
                'ordering': ['-percent'],
            },
        ),
        migrations.CreateModel(
            name='StockSymbolMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_code', models.BigIntegerField(db_index=True, unique=True)),
                ('l18', models.CharField(db_index=True, max_length=64)),
                ('l30', models.CharField(max_length=120)),
                ('l30_en', models.CharField(blank=True, default='', max_length=120)),
                ('isin', models.CharField(blank=True, default='', max_length=32)),
                ('code_12', models.CharField(blank=True, default='', max_length=32)),
                ('code_5', models.CharField(blank=True, default='', max_length=16)),
                ('code_4', models.CharField(blank=True, default='', max_length=16)),
                ('market', models.CharField(blank=True, default='', max_length=64)),
                ('market_board', models.CharField(blank=True, default='', max_length=120)),
                ('sector', models.CharField(blank=True, default='', max_length=120)),
                ('sector_sub', models.CharField(blank=True, default='', max_length=120)),
                ('shares_count', models.BigIntegerField(default=0)),
                ('base_volume', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('g_pe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ps', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('free_float', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['l18'],
            },
        ),
        migrations.CreateModel(
            name='StockTransactionTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('row', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('canceled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'row'],
            },
        ),
        migrations.AddConstraint(
            model_name='codalannouncement',
            constraint=models.UniqueConstraint(fields=('symbol', 'code', 'date_publish', 'time_publish'), name='uniq_codal_symbol_code_publish'),
        ),
        migrations.AddConstraint(
            model_name='dailystockhistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date', 'is_adjusted'), name='uniq_stock_history_symbol_date_adj'),
        ),
        migrations.AddConstraint(
            model_name='goldcurrencyhistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_gold_currency_history_symbol_date'),
        ),
        migrations.AddConstraint(
            model_name='marketcandle',
            constraint=models.UniqueConstraint(fields=('symbol', 'timeframe', 'date_time'), name='uniq_market_candle_symbol_tf_dt'),
        ),
        migrations.AddConstraint(
            model_name='marketindexdata',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='uniq_market_index_date_time'),
        ),
        migrations.AddConstraint(
            model_name='shareholderrecord',
            constraint=models.UniqueConstraint(fields=('symbol', 'date', 'shareholder_id'), name='uniq_shareholder_symbol_date_id'),
        ),
        migrations.AddConstraint(
            model_name='stocktransactiontick',
            constraint=models.UniqueConstraint(fields=('symbol', 'date', 'row'), name='uniq_stock_tick_symbol_date_row'),
        ),
    ]
