# Generated by Django 5.0.7 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiRequestQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(unique=True)),
                ("limit", models.PositiveIntegerField(default=9800)),
                ("used", models.PositiveIntegerField(default=0)),
                ("archive_used", models.PositiveIntegerField(default=0)),
                ("live_used", models.PositiveIntegerField(default=0)),
                ("other_used", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-day"]},
        ),
        migrations.CreateModel(
            name="ArchiveFetchState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(choices=[("stock_history_unadjusted", "Stock history unadjusted"), ("stock_history_adjusted", "Stock history adjusted"), ("stock_candle_unadjusted", "Stock candle unadjusted"), ("stock_candle_adjusted", "Stock candle adjusted"), ("gold_daily", "Gold daily")], max_length=40)),
                ("symbol", models.CharField(max_length=64)),
                ("expected_rows", models.PositiveIntegerField(default=0)),
                ("stored_rows", models.PositiveIntegerField(default=0)),
                ("missing_rows", models.PositiveIntegerField(default=0)),
                ("first_date", models.CharField(blank=True, default="", max_length=32)),
                ("last_date", models.CharField(blank=True, default="", max_length=32)),
                ("verified_complete", models.BooleanField(db_index=True, default=False)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={"ordering": ["verified_complete", "-missing_rows", "last_attempt_at"]},
        ),
        migrations.CreateModel(
            name="MarketInstrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("tsetmc", "TSETMC"), ("brs", "BRS")], max_length=8)),
                ("symbol", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=160)),
                ("category", models.CharField(choices=[("stock", "Stock"), ("gold", "Gold"), ("excluded", "Excluded")], max_length=16)),
                ("provider_group", models.CharField(blank=True, default="", max_length=64)),
                ("isin", models.CharField(blank=True, default="", max_length=32)),
                ("eligible", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["source", "symbol"]},
        ),
        migrations.AddConstraint(
            model_name="archivefetchstate",
            constraint=models.UniqueConstraint(fields=("endpoint", "symbol"), name="uniq_archive_endpoint_symbol"),
        ),
        migrations.AddConstraint(
            model_name="marketinstrument",
            constraint=models.UniqueConstraint(fields=("source", "symbol"), name="uniq_market_instrument_source_symbol"),
        ),
    ]
