# Generated by Django 5.0.7 on 2026-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_fetch_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='codalannouncement',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'General Disclosures'), (2, 'Periodic Financial Statements'), (3, 'Monthly Production & Sales'), (4, 'Board of Directors Report'), (5, 'Auditor Notes & Opinion'), (6, 'General Assembly Decision'), (7, 'Capital Increase Announcement'), (8, 'Monthly Investment Portfolio'), (9, 'Corporate Governance'), (10, 'Subsidiary Financial Statements'), (11, 'IPO & Bond Prospectus')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='codalannouncement',
            name='category_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='codalannouncement',
            name='is_audited',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
