# Generated by Django 5.2.16 on 2026-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_storage_tuning'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFetchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_key', models.CharField(db_index=True, max_length=40)),
                ('scope', models.CharField(blank=True, default='', max_length=64)),
                ('cadence_seconds', models.PositiveIntegerField()),
                ('session_only', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['endpoint_key', 'scope'],
                'indexes': [models.Index(fields=['enabled', 'next_attempt_at'], name='live_fetch_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('endpoint_key', 'scope'), name='uniq_live_fetch_endpoint_scope')],
            },
        ),
    ]
