# Generated by Django 5.0.7 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0003_codalannouncement_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefetchstate",
            name="endpoint",
            field=models.CharField(
                choices=[
                    ("stock_history_unadjusted", "Stock history unadjusted"),
                    ("stock_history_adjusted", "Stock history adjusted"),
                    ("stock_candle_unadjusted", "Stock candle unadjusted"),
                    ("stock_candle_adjusted", "Stock candle adjusted"),
                    ("gold_daily", "Gold daily"),
                    ("codal_announcements", "Codal financial disclosures"),
                    ("shareholder_records", "Shareholder roster data"),
                    ("stock_transaction_ticks", "Intraday trade ledgers"),
                ],
                max_length=40,
            ),
        ),
    ]
