# Generated by Django 5.0.7 on 2026-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_archive_fetch_state_endpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('close_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='CryptoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('close_price_usd', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('close_price_toman', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('volume_24h', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='EtfNavHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('nav_stat', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('nav_issue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('nav_cancel', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('market_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('discount_pct', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='OptionContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('ua_symbol', models.CharField(db_index=True, max_length=64)),
                ('strike_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expiry_date', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('settlement_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('open_interest', models.BigIntegerField(default=0)),
                ('notional_value', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.AlterField(
            model_name='archivefetchstate',
            name='endpoint',
            field=models.CharField(choices=[('stock_history_unadjusted', 'Stock history unadjusted'), ('stock_history_adjusted', 'Stock history adjusted'), ('stock_candle_unadjusted', 'Stock candle unadjusted'), ('stock_candle_adjusted', 'Stock candle adjusted'), ('gold_daily', 'Gold & currency daily'), ('crypto_daily', 'Cryptocurrency daily'), ('commodity_daily', 'Commodities daily'), ('market_index_daily', 'TSE market index daily'), ('etf_nav_daily', 'ETF funds NAV daily'), ('option_contract_daily', 'Options contract daily'), ('codal_announcements', 'Codal financial disclosures'), ('shareholder_records', 'Shareholder roster data'), ('stock_transaction_ticks', 'Intraday trade ledgers')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='commodityhistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_commodity_symbol_date'),
        ),
        migrations.AddConstraint(
            model_name='cryptohistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_crypto_symbol_date'),
        ),
        migrations.AddConstraint(
            model_name='etfnavhistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_etf_nav_symbol_date'),
        ),
        migrations.AddConstraint(
            model_name='optioncontracthistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_option_contract_symbol_date'),
        ),
    ]
