# Generated by Django 5.0.7 on 2026-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_commodityhistory_cryptohistory_etfnavhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(max_length=20)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('logger_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
