# Generated by Django 5.0.7 on 2026-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0006_systemlogevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlogevent',
            name='service',
            field=models.CharField(db_index=True, default='backend', max_length=50),
        ),
    ]
