# Generated by Django 5.0.7 on 2026-07-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0009_purge_unverifiable_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=64)),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('date', models.CharField(blank=True, default='', max_length=10)),
                ('reason', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('occurrences', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='stocktransactiontick',
            name='uniq_stock_tick_symbol_date_row',
        ),
        migrations.AddConstraint(
            model_name='stocktransactiontick',
            constraint=models.UniqueConstraint(fields=('symbol', 'date', 'row', 'time'), name='uniq_stock_tick_symbol_date_row_time'),
        ),
        migrations.AddConstraint(
            model_name='rejectedrecord',
            constraint=models.UniqueConstraint(fields=('endpoint', 'symbol', 'date', 'reason'), name='uniq_rejected_endpoint_symbol_date_reason'),
        ),
    ]
