# Generated by Django 5.0.7 on 2026-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0011_delete_impossible_gold_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealLegalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('buy_count_i', models.IntegerField(blank=True, null=True)),
                ('buy_count_n', models.IntegerField(blank=True, null=True)),
                ('sell_count_i', models.IntegerField(blank=True, null=True)),
                ('sell_count_n', models.IntegerField(blank=True, null=True)),
                ('buy_i_volume', models.BigIntegerField(blank=True, null=True)),
                ('buy_n_volume', models.BigIntegerField(blank=True, null=True)),
                ('sell_i_volume', models.BigIntegerField(blank=True, null=True)),
                ('sell_n_volume', models.BigIntegerField(blank=True, null=True)),
                ('buy_i_value', models.BigIntegerField(blank=True, null=True)),
                ('buy_n_value', models.BigIntegerField(blank=True, null=True)),
                ('sell_i_value', models.BigIntegerField(blank=True, null=True)),
                ('sell_n_value', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='reallegalhistory',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_real_legal_symbol_date'),
        ),
    ]
