# Generated by Django 5.0.7 on 2026-08-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0012_real_legal_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolIntegrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=8)),
                ('coverage_ratio', models.FloatField(default=0.0)),
                ('max_gap_days', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('passes_gate', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='goldcurrencyhistory',
            index=models.Index(fields=['symbol', 'date'], name='marketdata__symbol_51bcbf_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcandle',
            index=models.Index(fields=['timeframe', 'symbol', 'date_time'], name='marketdata__timefra_84d3c5_idx'),
        ),
    ]
