# Generated by Django 5.2.16 on 2026-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0020_compress_ticks_after_7_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodalDiscoveryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, unique=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('next_page', models.PositiveIntegerField(default=1)),
                ('verified_complete', models.BooleanField(db_index=True, default=False)),
                ('checks', models.PositiveSmallIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracing_no', models.BigIntegerField(unique=True)),
                ('letter_serial', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('letter_code', models.CharField(blank=True, default='', max_length=32)),
                ('letter_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_publish', models.CharField(db_index=True, max_length=10)),
                ('time_publish', models.CharField(blank=True, default='', max_length=8)),
                ('date_sent', models.CharField(blank=True, default='', max_length=10)),
                ('time_sent', models.CharField(blank=True, default='', max_length=8)),
                ('url', models.CharField(blank=True, default='', max_length=1024)),
                ('pdf_url', models.CharField(blank=True, default='', max_length=1024)),
                ('excel_url', models.CharField(blank=True, default='', max_length=1024)),
                ('xbrl_url', models.CharField(blank=True, default='', max_length=1024)),
                ('attachment_url', models.CharField(blank=True, default='', max_length=1024)),
                ('has_html', models.BooleanField(blank=True, null=True)),
                ('has_excel', models.BooleanField(blank=True, null=True)),
                ('has_pdf', models.BooleanField(blank=True, null=True)),
                ('has_xbrl', models.BooleanField(blank=True, null=True)),
                ('has_attachment', models.BooleanField(blank=True, null=True)),
                ('is_estimate', models.BooleanField(blank=True, null=True)),
                ('under_supervision', models.SmallIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
