# Generated by Django 5.0.7 on 2026-08-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0020_archive_gaps_gold_source_nullable_ohlc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048)),
                ('kind', models.CharField(choices=[('excel', 'Excel'), ('html', 'HTML'), ('pdf', 'PDF'), ('attachment', 'Attachment')], max_length=16)),
                ('s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('blocked_network', 'Blocked network'), ('blocked_storage', 'Blocked storage'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='archivefetchstate',
            name='archive_cursor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='archivefetchstate',
            name='target_window_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='reallegalhistory',
            name='quality',
            field=models.CharField(db_index=True, default='validated', max_length=24),
        ),
        migrations.AddField(
            model_name='reallegalhistory',
            name='reconciliation_error',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rejectedrecord',
            name='destination_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rejectedrecord',
            name='disposition',
            field=models.CharField(db_index=True, default='quarantined', max_length=24),
        ),
        migrations.AddField(
            model_name='rejectedrecord',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CodalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, choices=[(1, 'General Disclosures'), (2, 'Periodic Financial Statements'), (3, 'Monthly Production & Sales'), (4, 'Board of Directors Report'), (5, 'Auditor Notes & Opinion'), (6, 'General Assembly Decision'), (7, 'Capital Increase Announcement'), (8, 'Monthly Investment Portfolio'), (9, 'Corporate Governance'), (10, 'Subsidiary Financial Statements'), (11, 'IPO & Bond Prospectus')], db_index=True, null=True)),
                ('report_type', models.CharField(blank=True, default='', max_length=80)),
                ('letter_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('period_start', models.CharField(blank=True, default='', max_length=10)),
                ('period_end', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('is_audited', models.BooleanField(blank=True, null=True)),
                ('is_consolidated', models.BooleanField(default=False)),
                ('is_correction', models.BooleanField(default=False)),
                ('parser_version', models.CharField(default='1', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('parsed', 'Parsed'), ('needs_review', 'Needs review'), ('unsupported_template', 'Unsupported template'), ('blocked_network', 'Blocked network'), ('blocked_storage', 'Blocked storage'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('quality', models.CharField(choices=[('validated', 'Validated'), ('degraded', 'Degraded'), ('needs_review', 'Needs review'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=24)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='marketdata.codalannouncement')),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='marketdata.codalreport')),
            ],
            options={
                'ordering': ['-announcement__date_publish', '-announcement__time_publish'],
            },
        ),
        migrations.CreateModel(
            name='CodalParsedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('table_index', models.PositiveIntegerField(default=0)),
                ('headers', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('source_coordinates', models.JSONField(default=dict)),
                ('parser_version', models.CharField(default='1', max_length=32)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_tables', to='marketdata.codalartifact')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_tables', to='marketdata.codalreport')),
            ],
        ),
        migrations.AddField(
            model_name='codalartifact',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='marketdata.codalreport'),
        ),
        migrations.CreateModel(
            name='CodalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('section_index', models.PositiveIntegerField(default=0)),
                ('source_coordinates', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='marketdata.codalartifact')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='marketdata.codalreport')),
            ],
        ),
        migrations.CreateModel(
            name='CodalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_code', models.CharField(db_index=True, max_length=160)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=12, max_digits=38, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('period_start', models.CharField(blank=True, default='', max_length=10)),
                ('period_end', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('dimensions', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('quality', models.CharField(db_index=True, default='validated', max_length=24)),
                ('parser_version', models.CharField(default='1', max_length=32)),
                ('source_coordinates', models.JSONField(default=dict)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='marketdata.codalparsedtable')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='marketdata.codalreport')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='marketdata.codalsection')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workflow', models.CharField(db_index=True, max_length=80)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('endpoint', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('retry', 'Retry'), ('skipped', 'Skipped'), ('blocked_network', 'Blocked network'), ('blocked_storage', 'Blocked storage'), ('failed', 'Failed')], db_index=True, max_length=32)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('destination_table', models.CharField(blank=True, default='', max_length=128)),
                ('rows_received', models.PositiveIntegerField(default=0)),
                ('rows_accepted', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('http_attempts', models.PositiveSmallIntegerField(default=0)),
                ('quota_attempts', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'outcome', 'created_at'], name='marketdata__workflo_df3739_idx'), models.Index(fields=['endpoint', 'symbol', 'created_at'], name='marketdata__endpoin_0a5ba5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='codalparsedtable',
            constraint=models.UniqueConstraint(fields=('report', 'artifact', 'sheet_name', 'table_index'), name='uniq_codal_parsed_table'),
        ),
        migrations.AddConstraint(
            model_name='codalartifact',
            constraint=models.UniqueConstraint(fields=('report', 'kind', 'source_url'), name='uniq_codal_artifact_source'),
        ),
        migrations.AddConstraint(
            model_name='codalsection',
            constraint=models.UniqueConstraint(fields=('report', 'artifact', 'section_index'), name='uniq_codal_section'),
        ),
        migrations.AddIndex(
            model_name='codalfact',
            index=models.Index(fields=['fact_code', 'period_end', 'quality'], name='marketdata__fact_co_f4285f_idx'),
        ),
    ]
