# Generated by Django 5.2.16 on 2026-08-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0024_ingest_lineage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommodityHistory',
        ),
        migrations.DeleteModel(
            name='CryptoHistory',
        ),
        migrations.DeleteModel(
            name='EtfNavHistory',
        ),
        migrations.DeleteModel(
            name='OptionContractHistory',
        ),
    ]
