# Generated by Django 5.2.16 on 2026-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0025_delete_commodityhistory_delete_cryptohistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codalannouncement',
            name='classified_by',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='codalannouncement',
            name='doc_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='codalannouncement',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='codalannouncement',
            index=models.Index(fields=['symbol', 'tier'], name='codal_symbol_tier_idx'),
        ),
    ]
