# Generated by Django 5.2.16 on 2026-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0026_codal_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefetchstate',
            name='blacklisted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='archivefetchstate',
            name='last_probe_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivefetchstate',
            name='suspended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='archivefetchstate',
            name='suspension_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='archivefetchstate',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='archivefetchstate',
            index=models.Index(fields=['blacklisted', 'suspended_at', 'last_probe_at'], name='archive_probe_due_idx'),
        ),
    ]
