# Generated by Django 5.2.16 on 2026-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0028_autovacuum_thresholds'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailystockhistory',
            name='marketdata__symbol_7ee44e_idx',
        ),
        migrations.AlterField(
            model_name='dailystockhistory',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dailystockhistory',
            name='last_correlation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dailystockhistory',
            name='symbol',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='last_correlation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='marketcandle',
            name='symbol',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='reallegalhistory',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reallegalhistory',
            name='quality',
            field=models.CharField(default='validated', max_length=24),
        ),
        migrations.AlterField(
            model_name='reallegalhistory',
            name='symbol',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='stocktransactiontick',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransactiontick',
            name='symbol',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='dailystockhistory',
            index=models.Index(fields=['date'], name='stock_history_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactiontick',
            index=models.Index(fields=['date'], name='tick_date_idx'),
        ),
    ]
