# Generated by Django 5.2.16 on 2026-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0029_remove_dailystockhistory_marketdata__symbol_7ee44e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockhistory',
            name='ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketcandle',
            name='ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransactiontick',
            name='ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
