# Generated by Django 5.2.16 on 2026-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0038_delete_retired_aggregate_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldcurrencyhistory',
            name='source',
            field=models.CharField(choices=[('provider', 'Provider'), ('aggregate', 'Live-price aggregate (retired)')], default='provider', max_length=16),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='category',
            field=models.CharField(choices=[('stock', 'Stock'), ('gold', 'Gold'), ('crypto', 'Crypto'), ('commodity', 'Commodity'), ('etf', 'ETF'), ('excluded', 'Excluded')], max_length=16),
        ),
        migrations.CreateModel(
            name='MarketDailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('commodity', 'Commodity'), ('etf_nav', 'ETF NAV'), ('index', 'Market index'), ('tse_option', 'TSE option'), ('ime_future', 'IME future'), ('ime_option', 'IME option')], db_index=True, max_length=16)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('date', models.CharField(max_length=10)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('asset_class', 'symbol', 'date'), name='uniq_market_daily_bar')],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('commodity', 'Commodity'), ('etf_nav', 'ETF NAV')], db_index=True, max_length=16)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('provider_payload', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_class', 'symbol', '-observed_at'], name='marketdata__asset_c_98c629_idx')],
            },
        ),
    ]
