"""Management command to correct historical USDT_IRT 10× undervaluation.

Only corrects rows where ALL four OHLC fields are consistently ~10× lower than
the provider's quoted values. Uses an immutable manifest to ensure precision
and reversibility.

Usage:
    # Dry-run (default) - shows what would be changed
    python manage.py fix_usdt_irt_history

    # Apply with manifest verification
    python manage.py fix_usdt_irt_history --apply --manifest-hash <SHA256>

    # Generate manifest only
    python manage.py fix_usdt_irt_history --generate-manifest --output-manifest /path/to/manifest.csv
"""
import csv
import hashlib
import logging
import sys
from datetime import datetime
from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError
from django.db import connection, transaction
from django.core.cache import cache

logger = logging.getLogger(__name__)

# The exact confirmed row IDs (generated by create_manifest)
# This list is populated by --generate-manifest and must match exactly for --apply
MANIFEST_VERSION = "1.0"
CUTOFF_DATE = "1405-05-11"
SYMBOL = "USDT_IRT"
EXPECTED_COUNT = 992

# Named constants for ratio threshold (5% tolerance around 0.100)
LOWER_RATIO_LIMIT = 0.095
UPPER_RATIO_LIMIT = 0.105

# Ambiguous dates excluded from correction (ratio ~0.101 not 0.100)
AMBIGUOUS_DATES = frozenset(["1402-10-25", "1405-05-03"])

# Provider-unavailable dates (early series before provider history starts)
PROVIDER_GAP_DATES = frozenset([
    "1402-08-09", "1402-08-10", "1402-08-11", "1402-08-12",
    "1402-08-13", "1402-08-14", "1402-08-15", "1402-08-16",
    "1402-08-17", "1402-08-18",
])


class Command(BaseCommand):
    help = "Correct historical USDT_IRT 10× undervaluation using immutable manifest"

    def add_arguments(self, parser):
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Actually apply corrections (default is dry-run)",
        )
        parser.add_argument(
            "--manifest-hash",
            type=str,
            help="SHA-256 of the manifest CSV (required for --apply)",
        )
        parser.add_argument(
            "--generate-manifest",
            action="store_true",
            help="Generate the manifest CSV instead of running correction",
        )
        parser.add_argument(
            "--output-manifest",
            type=str,
            default="/tmp/usdt_irt_manifest.csv",
            help="Path for manifest output (default: /tmp/usdt_irt_manifest.csv)",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Explicit dry-run (default behavior)",
        )

    def handle(self, *args, **options):
        self.apply = options["apply"]
        self.manifest_hash = options["manifest_hash"]
        self.generate_manifest = options["generate_manifest"]
        self.output_manifest = options["output_manifest"]
        self.dry_run = options["dry_run"] or not self.apply

        if self.generate_manifest:
            self._generate_manifest()
            return

        if self.apply and not self.manifest_hash:
            raise CommandError("--manifest-hash is required when using --apply")

        if self.apply and self.dry_run:
            raise CommandError("Cannot use both --apply and --dry-run")

        # Verify database identity first
        self._verify_database()

        # Load and verify manifest
        manifest_rows = self._load_manifest()
        self._verify_manifest(manifest_rows)

        if self.dry_run:
            self._dry_run(manifest_rows)
        else:
            self._apply(manifest_rows)

    def _verify_database(self):
        """Confirm we're connected to the authoritative Docker Postgres."""
        with connection.cursor() as cursor:
            cursor.execute("SELECT current_database(), inet_server_addr(), pg_size_pretty(pg_database_size(current_database()))")
            db_name, addr, size = cursor.fetchone()
            self.stdout.write(f"Database: {db_name} at {addr} ({size})")
            if db_name not in ("portfolio", "test_portfolio", "portfolio_test"):
                raise CommandError(f"Expected database 'portfolio', got '{db_name}'")

    def _generate_manifest(self):
        """Generate the immutable manifest of 992 confirmed rows."""
        self.stdout.write("Generating USDT_IRT correction manifest...")

        with connection.cursor() as cursor:
            # Get all stored USDT_IRT rows with OHLC
            cursor.execute("""
                SELECT id, date, open_price, high_price, low_price, close_price, unit
                FROM marketdata_goldcurrencyhistory
                WHERE symbol = %s
                ORDER BY date
            """, [SYMBOL])
            stored_rows = cursor.fetchall()

        # Fetch provider data for verification
        provider_data = self._fetch_provider_data()

        manifest_rows = []
        excluded = {"ambiguous": 0, "provider_gap": 0, "post_cutoff": 0, "already_correct": 0}

        for row in stored_rows:
            row_id, date, open_p, high_p, low_p, close_p, unit = row

            # Skip post-cutoff
            if date >= CUTOFF_DATE:
                excluded["post_cutoff"] += 1
                continue

            # Skip ambiguous
            if date in AMBIGUOUS_DATES:
                excluded["ambiguous"] += 1
                continue

            # Skip provider gap
            if date in PROVIDER_GAP_DATES:
                excluded["provider_gap"] += 1
                continue

            # Verify against provider
            provider = provider_data.get(date)
            if not provider:
                excluded["provider_gap"] += 1
                continue

            # Check all 4 OHLC fields are ~10× lower
            ratios = {
                "open": float(open_p) / provider["open"] if provider["open"] else None,
                "high": float(high_p) / provider["high"] if provider["high"] else None,
                "low": float(low_p) / provider["low"] if provider["low"] else None,
                "close": float(close_p) / provider["close"] if provider["close"] else None,
            }

            # All ratios must be within 5% tolerance of 10x low (0.095 - 0.105)
            all_10x = all(r and LOWER_RATIO_LIMIT < r < UPPER_RATIO_LIMIT for r in ratios.values())
            if not all_10x:
                excluded["already_correct"] += 1
                continue

            manifest_rows.append({
                "id": row_id,
                "date": date,
                "unit": unit,
                "open_orig": str(open_p),
                "high_orig": str(high_p),
                "low_orig": str(low_p),
                "close_orig": str(close_p),
                "open_corrected": str(Decimal(str(open_p)) * 10),
                "high_corrected": str(Decimal(str(high_p)) * 10),
                "low_corrected": str(Decimal(str(low_p)) * 10),
                "close_corrected": str(Decimal(str(close_p)) * 10),
                "provider_open": str(provider["open"]),
                "provider_high": str(provider["high"]),
                "provider_low": str(provider["low"]),
                "provider_close": str(provider["close"]),
            })

        # Write manifest CSV
        fieldnames = [
            "id", "date", "unit",
            "open_orig", "high_orig", "low_orig", "close_orig",
            "open_corrected", "high_corrected", "low_corrected", "close_corrected",
            "provider_open", "provider_high", "provider_low", "provider_close",
        ]

        with open(self.output_manifest, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(manifest_rows)

        # Compute SHA-256
        with open(self.output_manifest, "rb") as f:
            sha256 = hashlib.sha256(f.read()).hexdigest()

        self.stdout.write(f"Manifest written to {self.output_manifest}")
        self.stdout.write(f"Rows: {len(manifest_rows)}")
        self.stdout.write(f"SHA-256: {sha256}")
        self.stdout.write(f"Excluded: {excluded}")
        self.stdout.write(f"Expected count: {EXPECTED_COUNT}")
        self.stdout.write(f"Version: {MANIFEST_VERSION}")

        if len(manifest_rows) != EXPECTED_COUNT:
            self.stderr.write(self.style.ERROR(f"Row count mismatch: got {len(manifest_rows)}, expected {EXPECTED_COUNT}"))
            raise CommandError(f"Row count mismatch: got {len(manifest_rows)}, expected {EXPECTED_COUNT}")

    def _fetch_provider_data(self):
        """Fetch current provider data for USDT_IRT."""
        from marketdata.fetchers.gold_currency import fetch_gold_currency_pro_history_daily
        from django.conf import settings

        payload = fetch_gold_currency_pro_history_daily(settings.BRS_API_KEY, SYMBOL)
        provider_data = {}
        if payload and "history_daily" in payload:
            for row in payload["history_daily"]:
                date = row["date"].replace("/", "-")
                provider_data[date] = {
                    "open": float(row["open"]),
                    "high": float(row["high"]),
                    "low": float(row["low"]),
                    "close": float(row["close"]),
                }
        return provider_data

    def _load_manifest(self):
        """Load manifest from the standard location."""
        manifest_path = self.output_manifest
        rows = []
        with open(manifest_path, "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append(row)
        return rows

    def _verify_manifest(self, manifest_rows):
        """Verify manifest matches expected criteria."""
        # Check count
        if len(manifest_rows) != EXPECTED_COUNT:
            raise CommandError(f"Manifest has {len(manifest_rows)} rows, expected {EXPECTED_COUNT}")

        # Check hash if provided
        if self.manifest_hash:
            with open(self.output_manifest, "rb") as f:
                actual_hash = hashlib.sha256(f.read()).hexdigest()
            if actual_hash != self.manifest_hash:
                raise CommandError(f"Manifest hash mismatch: expected {self.manifest_hash}, got {actual_hash}")

        # Verify no duplicate IDs
        ids = [r["id"] for r in manifest_rows]
        if len(ids) != len(set(ids)):
            raise CommandError("Manifest contains duplicate IDs")

        self.stdout.write(f"Manifest verified: {len(manifest_rows)} rows, hash OK")

    def _dry_run(self, manifest_rows):
        """Show what would be changed without making changes."""
        self.stdout.write(self.style.NOTICE("=== DRY RUN ==="))

        # Verify current DB values still match manifest
        mismatches, pending_ids, already_corrected_ids = self._verify_current_values(manifest_rows)
        if mismatches:
            self.stdout.write(self.style.ERROR(f"FAIL: {len(mismatches)} rows have unexpected current values"))
            for m in mismatches[:5]:
                if "error" in m:
                    self.stdout.write(f"  ID {m['id']}: {m['error']}")
                else:
                    self.stdout.write(f"  ID {m['id']}: expected open={m['expected_open']}, got={m['actual_open']}")
            raise CommandError(f"FAIL: {len(mismatches)} rows have unexpected current values")

        self.stdout.write(f"Would update {len(pending_ids)} rows ({len(already_corrected_ids)} already match manifest corrected values)")
        self.stdout.write("All current values match manifest. Ready to apply.")
        self.stdout.write(f"Sample (first 3):")
        pending_rows = [r for r in manifest_rows if int(r["id"]) in pending_ids]
        for row in pending_rows[:3]:
            self.stdout.write(
                f"  {row['date']} (id={row['id']}): "
                f"open {row['open_orig']}->{row['open_corrected']}, "
                f"high {row['high_orig']}->{row['high_corrected']}, "
                f"low {row['low_orig']}->{row['low_corrected']}, "
                f"close {row['close_orig']}->{row['close_corrected']}"
            )

        # Also show what is NOT being changed
        self._show_unchanged_categories()

    def _verify_current_values(self, manifest_rows):
        """Verify database values still match manifest before-values or corrected values."""
        mismatches = []
        pending_ids = []
        already_corrected_ids = []
        ids = [int(r["id"]) for r in manifest_rows]

        with connection.cursor() as cursor:
            placeholders = ",".join(["%s"] * len(ids))
            cursor.execute(f"""
                SELECT id, open_price, high_price, low_price, close_price
                FROM marketdata_goldcurrencyhistory
                WHERE id IN ({placeholders})
            """, ids)
            current = {row[0]: row[1:] for row in cursor.fetchall()}

        for row in manifest_rows:
            row_id = int(row["id"])
            if row_id not in current:
                mismatches.append({"id": row_id, "error": "Row not found"})
                continue
            actual_open, actual_high, actual_low, actual_close = current[row_id]
            expected_open = Decimal(row["open_orig"])
            expected_high = Decimal(row["high_orig"])
            expected_low = Decimal(row["low_orig"])
            expected_close = Decimal(row["close_orig"])

            corrected_open = Decimal(row["open_corrected"])
            corrected_high = Decimal(row["high_corrected"])
            corrected_low = Decimal(row["low_corrected"])
            corrected_close = Decimal(row["close_corrected"])

            matches_orig = (actual_open == expected_open and actual_high == expected_high and
                            actual_low == expected_low and actual_close == expected_close)
            matches_corr = (actual_open == corrected_open and actual_high == corrected_high and
                            actual_low == corrected_low and actual_close == corrected_close)

            if matches_corr:
                already_corrected_ids.append(row_id)
            elif matches_orig:
                pending_ids.append(row_id)
            else:
                mismatches.append({
                    "id": row_id,
                    "expected_open": str(expected_open), "actual_open": str(actual_open),
                    "expected_high": str(expected_high), "actual_high": str(actual_high),
                    "expected_low": str(expected_low), "actual_low": str(actual_low),
                    "expected_close": str(expected_close), "actual_close": str(actual_close),
                })

        return mismatches, pending_ids, already_corrected_ids

    def _show_unchanged_categories(self):
        """Show counts of rows deliberately not changed."""
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT date FROM marketdata_goldcurrencyhistory
                WHERE symbol = %s ORDER BY date
            """, [SYMBOL])
            all_dates = [r[0] for r in cursor.fetchall()]

        pre_cutoff = sum(1 for d in all_dates if d < CUTOFF_DATE)
        post_cutoff = sum(1 for d in all_dates if d >= CUTOFF_DATE)
        ambiguous = sum(1 for d in all_dates if d in AMBIGUOUS_DATES)
        provider_gap = sum(1 for d in all_dates if d in PROVIDER_GAP_DATES)

        self.stdout.write(f"\nUnchanged categories:")
        self.stdout.write(f"  Post-cutoff (>= {CUTOFF_DATE}): {post_cutoff}")
        self.stdout.write(f"  Ambiguous (ratio ~0.101): {ambiguous}")
        self.stdout.write(f"  Provider gap (early dates): {provider_gap}")
        self.stdout.write(f"  Total pre-cutoff: {pre_cutoff}")

    def _apply(self, manifest_rows):
        """Apply the corrections in a single transaction."""
        self.stdout.write(self.style.NOTICE("=== APPLYING CORRECTIONS ==="))

        # Verify current values one more time
        mismatches, pending_ids, already_corrected_ids = self._verify_current_values(manifest_rows)
        if mismatches:
            for m in mismatches[:5]:
                if "error" in m:
                    self.stdout.write(f"  ID {m['id']}: {m['error']}")
                else:
                    self.stdout.write(f"  ID {m['id']}: expected open={m['expected_open']}, got={m['actual_open']}")
            raise CommandError(f"Abort: {len(mismatches)} rows have unexpected current values")

        if not pending_ids:
            self.stdout.write("All rows already match manifest corrected values. Updated 0 rows.")
            return

        # Create rollback snapshot (only for pending rows)
        pending_rows = [r for r in manifest_rows if int(r["id"]) in pending_ids]
        snapshot_path = self._create_rollback_snapshot(pending_rows)

        # Apply updates
        placeholders = ",".join(["%s"] * len(pending_ids))

        updated = 0
        with transaction.atomic():
            with connection.cursor() as cursor:
                # Lock rows
                cursor.execute(f"""
                    SELECT id FROM marketdata_goldcurrencyhistory
                    WHERE id IN ({placeholders})
                    FOR UPDATE
                """, pending_ids)

                # Update all 4 OHLC fields
                cursor.execute(f"""
                    UPDATE marketdata_goldcurrencyhistory
                    SET
                        open_price = open_price * 10,
                        high_price = high_price * 10,
                        low_price = low_price * 10,
                        close_price = close_price * 10
                    WHERE id IN ({placeholders})
                """, pending_ids)
                updated = cursor.rowcount

        # Invalidate caches
        self._invalidate_caches()

        # Verify results
        self._verify_results(manifest_rows)

        self.stdout.write(self.style.SUCCESS(f"SUCCESS: Updated {updated} rows"))
        self.stdout.write(f"Rollback snapshot: {snapshot_path}")

        if updated != EXPECTED_COUNT:
            raise CommandError(f"Count mismatch: updated {updated}, expected {EXPECTED_COUNT}")

    def _create_rollback_snapshot(self, manifest_rows):
        """Create a rollback snapshot with before-values."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        snapshot_path = f"/tmp/usdt_irt_rollback_{timestamp}.csv"

        ids = [int(r["id"]) for r in manifest_rows]
        placeholders = ",".join(["%s"] * len(ids))

        with connection.cursor() as cursor:
            cursor.execute(f"""
                SELECT id, date, open_price, high_price, low_price, close_price, unit
                FROM marketdata_goldcurrencyhistory
                WHERE id IN ({placeholders})
                ORDER BY date
            """, ids)
            rows = cursor.fetchall()

        with open(snapshot_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["id", "date", "open_price", "high_price", "low_price", "close_price", "unit"])
            writer.writerows(rows)

        # Verify snapshot
        with open(snapshot_path, "rb") as f:
            sha256 = hashlib.sha256(f.read()).hexdigest()

        self.stdout.write(f"Rollback snapshot: {snapshot_path} ({len(rows)} rows, SHA-256: {sha256})")
        return snapshot_path

    def _invalidate_caches(self):
        """Invalidate relevant caches after correction."""
        # Invalidate price version fingerprint (affects returns cache)
        from portfolio.services.returns import _price_version_fingerprint
        from portfolio.services.valuation import invalidate_prices_cache

        # The fingerprint includes GoldCurrencyHistory, so it will naturally change
        # But we also explicitly invalidate the live prices cache
        invalidate_prices_cache()

        # Clear any cached returns matrices
        from portfolio.services.returns import invalidate_returns_cache
        invalidate_returns_cache()

        # Clear any cached returns matrices
        from django.core.cache import cache
        # We can't easily enumerate all cache keys, but the version fingerprint
        # ensures new cache keys will be used

        self.stdout.write("Caches invalidated (live prices, returns version fingerprint updated)")

    def _verify_results(self, manifest_rows):
        """Verify post-update values match expected corrected values."""
        ids = [int(r["id"]) for r in manifest_rows]
        placeholders = ",".join(["%s"] * len(ids))

        with connection.cursor() as cursor:
            cursor.execute(f"""
                SELECT id, open_price, high_price, low_price, close_price
                FROM marketdata_goldcurrencyhistory
                WHERE id IN ({placeholders})
            """, ids)
            actual = {row[0]: row[1:] for row in cursor.fetchall()}

        for row in manifest_rows:
            row_id = int(row["id"])
            if row_id not in actual:
                raise CommandError(f"Row {row_id} missing after update")

            act_open, act_high, act_low, act_close = actual[row_id]
            exp_open = Decimal(row["open_corrected"])
            exp_high = Decimal(row["high_corrected"])
            exp_low = Decimal(row["low_corrected"])
            exp_close = Decimal(row["close_corrected"])

            if (act_open != exp_open or act_high != exp_high or
                act_low != exp_low or act_close != exp_close):
                raise CommandError(
                    f"Row {row_id} value mismatch: "
                    f"open={act_open}/{exp_open}, high={act_high}/{exp_high}, "
                    f"low={act_low}/{exp_low}, close={act_close}/{exp_close}"
                )

        self.stdout.write("All 992 rows verified: OHLC values match manifest corrected values")